'use strict';

export const ACTION_LOAD_USERS = 'ACTION_LOAD_USERS';
export const ACTION_SHOW_USER = 'ACTION_SHOW_USER';
export const ACTION_ADD_USER = 'ACTION_ADD_USER';
export const ACTION_REMOVE_USER = 'ACTION_REMOVE_USER';
export const ACTION_UPDATE_USER = 'ACTION_UPDATE_USER';
export const ACTION_NEW_USER = 'ACTION_NEW_USER';
export const ACTION_EDIT_USER = 'ACTION_EDIT_USER';
export const ACTION_DELETE_USER = 'ACTION_DELETE_USER';
export const ACTION_SAVE_USER = 'ACTION_SAVE_USER';
